index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

add_user:
    path: /user/publish
    methods: POST
    controller: App\Controller\UserController::registerUser

show_katalog:
    path: /user/{userId}
    methods: GET
    controller: App\Controller\StorefrontController::index