index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

login:
    path: /user/login
    methods: POST
    controller: App\Controller\UserController::loginUser

add_user:
    path: /user/register
    methods: POST
    controller: App\Controller\UserController::registerUser

show_login:
    path: /login
    controller: App\Controller\UserController::showLogin

show_katalog:
    path: /user/{userId}
    methods: GET
    controller: App\Controller\StorefrontController::index

order:
    path: /order/{pizzaId}
    methods: GET
    controller: App\Controller\OrderController::index

make_order:
    path: /order/make
    methods: POST
    controller: App\Controller\OrderController::makeOrder

add_pizza:
    path: /pizza/publish
    methods: POST
    controller: App\Controller\StorefrontController::addPizza

del_pizza:
    path: /pizza/del
    methods: POST
    controller: App\Controller\StorefrontController::delPizza
