index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

login:
    path: /user/login
    methods: POST
    controller: App\Controller\UserController::loginUser

add_user:
    path: /user/register
    methods: POST
    controller: App\Controller\UserController::registerUser

show_login:
    path: /login
    controller: App\Controller\UserController::showLogin

show_katalog:
    path: /user/{userId}
    methods: GET
    controller: App\Controller\StorefrontController::index